# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e441813b42d7d81126a5cb75355d12c0b85dddde2bdc9693391cea50f2a702f8a244ed4d372782190745c84da3230cfe4de9820d08a0b9f7503db3af294ceff

test:
  secret_key_base: 3ab093ff937ba5e84521a5f23220949b682e8811a7daed8fe7c14c792478c8ed1b8df80613083b6717583ee3ebac52d1748ab20a887f321f17e07eebd0ea9dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
